name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows:
    uses: logos-co/logos-windows-ci/.github/workflows/windows-ci.yml@v1
    secrets: inherit
    with:
      targets: default
      cold-derivation-budget: 170
